version: '3.1'
services:
  stats-server:
    build: stat-service
    container_name: ewm-stat-service
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm_stat

  stats-db:
    image: postgres:13.7-alpine
    container_name: postgresql-stats
    ports:
      - "6789:5432"
    environment:
      - POSTGRES_DB=ewm_stat
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-service:
    build: main-service
    container_name: ewm-main-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm_main
      - stats-server.url:http://ewm-stat-service:9090

  ewm-db:
    image: postgres:13.7-alpine
    container_name: postgresql-main
    ports:
      - "6543:5432"
    environment:
      - POSTGRES_DB=ewm_main
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
